### ISSUE TITLE
System properties mechanism doesn't work from included files

### ISSUE THREAD

**Issue by marcinkp** [Knotx/knotx-launcher#8]
**Describe the bug**
Substitution is not resolved for properties withing included configuration

**To Reproduce**
1. In application conf define
```
global {
  profile{
    include required("includes/profile-active.conf")
  }
}
...
config.server.options.config {
  somevalue = ${global.profile.somevalue}
}
```
2. profile-active.conf has:
```
somevalue =  ${custom.system.property}
```
3. Execute
```
./bin/knotx.bat run-knotx -Dcustom.system.property=myvalue
```

Could not resolve substitution to a value: ${global.profile.custom.system.property}

**Comment by tomaszmichalak** [comment]
@marcinkp Can you please implement Unit test?

**Comment by marcinkp** [comment]
In fact it is not an issue. Its specific HOCON implementation. See: https://github.com/lightbend/config/blob/master/HOCON.md#include-semantics-substitution

I prepared unit test which cover this scenario.
